  # Docker
  # Build and push an image to Azure Container Registry
  # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

  trigger:
    - main

  resources:
    - repo: self

  variables:
    #Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: 'ACRServiceConnection'
    imageRepository: 'simulationDeployPOCACR'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: '$(Build.BuildId)'

    #Storage Account Details for storing state file
    backendServiceArm: 'MyServiceConnection'
    backendAzureRmResourceGroupName: 'cicdpocrg'
    backendAzureRmStorageAccountName: 'terraformpocsa'
    backendAzureRmContainerName: 'terraform-state'
    backendAzureRmKey: 'tf/terraform.tfstate'

    environment: 'development'
    terraform_version: '1.0.10'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'
    DOCKER_BUILDKIT: 1

  stages:
  - stage: terraform_base
    jobs:
      - template: templates/terraform-apply.yaml
        parameters:
          backendServiceArm: '${{ variables.backendServiceArm }}'
          backendAzureRmResourceGroupName: '${{ variables.backendAzureRmResourceGroupName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/platform/terraform_cr/'
          backendAzureRmStorageAccountName: '${{ variables.backendAzureRmStorageAccountName }}'
          backendAzureRmContainerName: '${{ variables.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ variables.backendAzureRmKey }}'
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}

  - stage: Build
    dependsOn: [ terraform_base ]
    displayName: Build and push stage
    jobs:
      - template: templates/docker.yaml
        parameters:
          repository: ${{ variables.imageRepository }}
          dockerfile: ${{ variables.dockerfilePath }}
          containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
          tag: ${{ variables.tag }}

  - stage: terraform_aci_deploy
    dependsOn: [ Build ]
    displayName:  Deploy Image to Container
    jobs:
      -template: templates/terraform-apply.yaml
      parameters:
          backendServiceArm: '${{ variables.backendServiceArm }}'
          backendAzureRmResourceGroupName: '${{ variables.backendAzureRmResourceGroupName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/platform/terraform_aci/'
          backendAzureRmStorageAccountName: '${{ variables.backendAzureRmStorageAccountName }}'
          backendAzureRmContainerName: '${{ variables.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ variables.backendAzureRmKey }}'
          environment: ${{ variables.environment }}
          terraform_version: ${{ variables.terraform_version }}
